# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322352ff4eeef7757a3dbc53d0696970386004f0b18ad758f31af2c2110267d54eff46a17e224a2655b482c43f8fc19219f0cd5e35ec5e3f879045e3f2a98709
  oauth_client_id: 829494619030-0hfinpd6nfn6v8auqmnthkknhvu8b46e.apps.googleusercontent.com
  oauth_client_secret: odPpUtEVCpqIX6HaM5zwMO04

test:
  secret_key_base: 96bbd3d2f60e09911a56856c27706eac763ccdc06af064f8ba3c21816f7e32afd58b0bcb9cb8baebccd190791afee6aac82457804b8ee3771d95129a7da27fc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  oauth_client_id: <%= ENV["OAUTH_CLIENT_ID"] %>
  oauth_client_secret: <%= ENV["OAUTH_CLIENT_SECRET"] %>
